GET http://localhost:3000/posts

###
POST http://localhost:3000/posts
Content-Type: application/json

  {
    "title": "Knasboll majsboll chockladboll.",
    "views": 100
  }

###
DELETE http://localhost:3000/posts/12
Content-Type: application/json

